# Numpy

__Авторы задач: Блохин Н.В. (NVBlokhin@fa.ru), Макрушин С.В. (SVMakrushin@fa.ru)__

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html
* Уэс Маккини. Python и анализ данных

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

__При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.__

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np

In [13]:
minutes_n_ingredients_full = np.loadtxt('Подготовка к ТОБД/01_numpy_data/minutes_n_ingredients.csv')

ValueError: could not convert string to float: 'id,minutes,n_ingredients'

In [4]:
minutes_n_ingredients = np.loadtxt('Подготовка к ТОБД/01_numpy_data/minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
print(minutes_n_ingredients[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [5]:
mean_minutes_n_ingredients = np.mean(minutes_n_ingredients[:, 1:], axis=0)
min_minutes_n_ingredients = np.min(minutes_n_ingredients[:, 1:], axis=0)
max_minutes_n_ingredients = np.max(minutes_n_ingredients[:, 1:], axis=0)
median_minutes_n_ingredients = np.median(minutes_n_ingredients[:, 1:], axis=0)

3. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [9]:
random_recipes = np.random.choice(minutes_n_ingredients.shape[0], 10, replace=False) # replace=False - без повторений, minutes_n_ingredients.shape[0] - количество строк, 10 - количество выборок
print(minutes_n_ingredients[random_recipes])

[[130364    180      5]
 [406939     35     11]
 [148810      5      8]
 [289509     15      7]
 [108886     40      8]
 [189370     50      7]
 [107017     65     12]
 [171970    105     10]
 [ 15086     55      5]
 [ 51916    200      9]]


4. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [16]:
new_recipes = minutes_n_ingredients[minutes_n_ingredients[:, 2] <= 5] # [:, 2] - 3 столбец, : - все строки, 2 - индекс столбца
new_recipes

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

5. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [17]:
recipes_with_min = minutes_n_ingredients[minutes_n_ingredients[:, 2] < np.mean(minutes_n_ingredients[:, 2])]
print(recipes_with_min.shape[0] / minutes_n_ingredients.shape[0] * 100)

58.802


6. Вычислите значение $q_{0.75}$ третьего квартиля продолжительности выполнения рецепта. Замените в этом столбце значения, большие чем $q_{0.75}$ на величину $q_{0.75}$.

In [20]:
quartile_75 = np.quantile(minutes_n_ingredients[:, 1], 0.75)
minutes_n_ingredients[minutes_n_ingredients[:, 1] > quartile_75] = quartile_75 
minutes_n_ingredients

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [    65,     65,     65]], dtype=int32)

7. Посчитайте, для скольких рецептов исходного массива указана продолжительность, равная нулю. Модифицируйте исходный массив, заменив для таких строк значение в данном столбце на 1.

In [21]:
recipes_with_zero = minutes_n_ingredients[minutes_n_ingredients[:, 1] == 0]
print(recipes_with_zero.shape[0])

479


In [23]:
minutes_n_ingredients[minutes_n_ingredients[:, 1] == 0] = 1
minutes_n_ingredients

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [    65,     65,     65]], dtype=int32)

In [24]:
recipes_with_zero = minutes_n_ingredients[minutes_n_ingredients[:, 1] == 0]
print(recipes_with_zero.shape[0])

0


8. Найдите множество возможных значений величины количества ингредиентов и количество вхождений каждого из уникальных значений в набор данных. Используя `numpy.isin`, выясните, какие числа из отрезка [1, 41] отсуствуют в данном множестве и выведите их на экран. 

In [25]:
count_ingredients = np.unique(minutes_n_ingredients[:, 2], return_counts=True) 
print(count_ingredients)

print(np.isin(np.arange(1, 42), count_ingredients[0], invert=True))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 33, 34, 65],
      dtype=int32), array([  491,   790,  2536,  4777,  6687,  7654,  8446,  8474,  8106,
        7022,  5809,  4568,  3352,  2317,  1568,  1055,   676,   413,
         277,   175,    88,    64,    33,    27,    26,     7,     5,
           5,     7,     4,     1,     1, 24539]))
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True  True False False  True  True
  True  True  True  True  True]


9. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [26]:
time_per_ingredient = minutes_n_ingredients[:, 2] / minutes_n_ingredients[:, 1]
print(np.max(time_per_ingredient))

23.0


10. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [27]:
mean_ingredients_top_100 = np.mean(minutes_n_ingredients[np.argsort(minutes_n_ingredients[:, 1])][-100:, 2]) 
print(mean_ingredients_top_100)

61.12


11. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае. Выведите процент "простых" рецептов в датасете.

In [32]:
easy_recipes = (minutes_n_ingredients[:, 1] <= 20) & (minutes_n_ingredients[:, 2] <= 5) # создаем массив булевых значений
new_data = np.hstack((minutes_n_ingredients, easy_recipes.reshape(-1, 1))) # добавляем столбец к исходному массиву
print(new_data)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [    65     65     65      0]]


12. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет не менее 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [38]:
short_recipes = minutes_n_ingredients[minutes_n_ingredients[:, 1] < 10]
standard_recipes = minutes_n_ingredients[(minutes_n_ingredients[:, 1] >= 10) & (minutes_n_ingredients[:, 1] < 20)]
long_recipes = minutes_n_ingredients[minutes_n_ingredients[:, 1] >= 20]

13. Пусть в среднем одна минута работы повара стоит ресторану 5 ед., а средняя стоимость одного ингредиента составляет 10 ед. 
Создайте вектор-столбец `numpy`, содержащий данную информацию. Посчитайте среднюю стоимость приготовления для каждого из первых 10 рецептов в наборе данных.

In [37]:
mean_work = 5
mean_cost_ingredient = 10
cost = np.array([mean_work, mean_cost_ingredient])
print(cost)

cost_recipes = minutes_n_ingredients[:10, 1:3] @ cost
print(cost_recipes)

[ 5 10]
[460 195 110  85 440 270 180 125 125 170]
